EuroSpaceCenter/Controllers/PlanController.cs
using EuroSpaceCenter.Models;
using EuroSpaceCenter.util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace EuroSpaceCenter.Controllers {
    [Authorize]
    public class PlanController : Controller {

        public ActionResult Index() {
            List<users_has_parkplan> all = parkplan.GetAll(user.Get(User.Identity.Name).id);
            var accepted = all.Where(uhp => uhp.accepted).Select(uhp => uhp.parkplan);
            ViewBag.UnAccepted = all.Where(uhp => !uhp.accepted).Select(uhp => uhp.parkplan);
            return View(accepted);
        }

        // plans are public on purpose
        public ActionResult Detail(int id) {
            var plan = parkplan.Get(parkplan_id: id);
            ViewBag.Items = item.GetAll();
            ViewBag.PlanItems = plan.parkplans_has_items.ToList();
            ViewBag.Users = plan.users_has_parkplans.Select(t => t.user);
            return View(plan);
        }

        public HttpStatusCodeResult Set(int id) {
            if (parkplan.HasUser(user_id: user.Get(User.Identity.Name).id, parkplan_id: id)) {
                Session.Add("plan", new { id = id });
                return new HttpStatusCodeResult(200);
            } else {
                return new HttpStatusCodeResult(403);
            }
        }

        public ActionResult Create() {
            return View();
        }

        [HttpPost]
        public HttpStatusCodeResult Delete(int id) {
            try {
                if (parkplan.HasUser(user_id: user.Get(User.Identity.Name).id, parkplan_id: id)) {
                    parkplan.Delete(id);
                    return new HttpStatusCodeResult(204);
                } else {
                    return new HttpStatusCodeResult(403);
                }
            } catch (Exception) {
                return new HttpStatusCodeResult(500);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(parkplan plan) {
            if (TryValidateModel(plan)) {
                var p = plan.Create(user.Get(User.Identity.Name).id);
                return RedirectToAction("Detail", new { id = p.id });
            }
            return View(plan);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Invite(int id, string email) {
            // parkplan needs to be yours
            if (parkplan.HasUser(parkplan_id: id, user_id: user.Get(User.Identity.Name).id)) {
               try {
                    var u = user.Get(email);
                    // does invitee exist?
                    if (u == null) {
                        Email.Send(email, null, $"Your friend just signed you up for ESC, but you didn't have an account yet. You can Register at this link", "Log In", "http://eurospacecenter.haroenviaene.ikdoeict.be/Register/Index?plan=" + id, "Invited");
                        Flash.Set(TempData, "This user didn't have an account yet, they are invited now!");
                        return RedirectToAction("Detail", new { id = id });
                    } else {
                        parkplan.Invite(users_id: u.id, parkplan_id: id);
                        Flash.Set(TempData, "Invited");
                        return RedirectToAction("Detail", new { id = id });
                    }
                } catch (Exception e) {
                    Flash.Set(TempData, "That didn't work 😲");
                    return RedirectToAction("Detail", new { id = id });
                }
            }
            Flash.Set(TempData, "That's not your plan 💁");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Add(int id, int item_id) {
            try {
                if (parkplan.HasUser(parkplan_id: id, user_id: user.Get(User.Identity.Name).id)) {
                    int has_id = parkplan.AddItem(id, item_id);
                    return Json(new { id = has_id });
                }
                return new HttpStatusCodeResult(403);
            } catch {
                return new HttpStatusCodeResult(500);
            }
        }

        [HttpPost]
        public HttpStatusCodeResult Remove(int id, int plan_has_item) {
            if (parkplan.HasUser(parkplan_id: id, user_id: user.Get(User.Identity.Name).id)) {
                parkplan.RemoveItem(plan_has_item);
                return new HttpStatusCodeResult(204);
            }
            return new HttpStatusCodeResult(403);
        }

        [HttpPost]
        public HttpStatusCodeResult Accept(int id) {
            if (parkplan.HasUser(parkplan_id: id, user_id: user.Get(User.Identity.Name).id)) {
                parkplan.Accept(user.Get(User.Identity.Name).id, id);
                return new HttpStatusCodeResult(200);
            }
            return new HttpStatusCodeResult(403);
        }

        [HttpPost]
        public HttpStatusCodeResult Reject(int id) {
            if (parkplan.HasUser(parkplan_id: id, user_id: user.Get(User.Identity.Name).id)) {
                parkplan.Reject(user.Get(User.Identity.Name).id, id);
                return new HttpStatusCodeResult(204);
            }
            return new HttpStatusCodeResult(403);
        }
    }
}

EuroSpaceCenter/Controllers/SearchController.cs
using EuroSpaceCenter.Models;
using System.Linq;
using System.Web.Mvc;

namespace EuroSpaceCenter.Controllers {
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult Index(string cat)
        {
            if (cat != null) {
                // zoek categorien
                try {
                    ViewBag.Items = item.Get(cat);
                } catch {
                    ViewBag.Items = item.GetAll();
                }
            } else {
                ViewBag.Items = item.GetAll();
            }
            ViewBag.Cat = cat;
            return View();
        }
    }
}

EuroSpaceCenter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="/Content/icon/apple-touch-icon.png">
    <link rel="icon" type="image/png" href="/Content/icon/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/Content/icon/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/Content/icon/manifest.json">
    <link rel="mask-icon" href="/Content/icon/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="/Content/icon/favicon.ico">
    <meta name="msapplication-config" content="/Content/icon/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
    <title>@ViewBag.Title - Euro Space center</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"><span class='thelastcall'>Euro Space Center</span><span class='emoji'>🚀</span></a>
            </div>
            <nav class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("What to do", "Index", "Search")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (User.IsInRole("admin")) {
                        <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                    }
                </ul>
                @if (User.Identity.IsAuthenticated) {
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@User.Identity.Name<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Account", "Index", "Account", null, new { @class = (ViewContext.RouteData.Values["controller"].ToString() == "Account" && ViewContext.RouteData.Values["action"].ToString() == "account" ? "active" : "") })</li>
                                <li>@Html.ActionLink("Park plans", "Index", "Plan")</li>
                                <li>@Html.ActionLink("Logout", "Logout", "Account", null, new { @class = (ViewContext.RouteData.Values["controller"].ToString() == "Login" && ViewContext.RouteData.Values["action"].ToString() == "logout" ? "active" : "") })</li>
                            </ul>
                        </li>
                    </ul>
                } else {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Login", "Login", "Account", null, new { @class = (ViewContext.RouteData.Values["controller"].ToString() == "Login" ? "active" : "") })</li>
                        <li><a href="/Account/Register">Register</a></li>
                    </ul>
                }
            </nav>
        </div>
    </div>
    <div class="container body-content">
        @if (TempData.ContainsKey("message")) {
            <div class="alert alert-info alert-dismissable">
                @TempData["message"]
            </div>
        }
        <main>@RenderBody()</main>
    </div>
    <footer class="clearfix footer container">
        <div class="pull-left">
            <a href="#"><img style="max-height: 40px" src="/Content/logo_adventureworld_color.png"></a>
        </div>
        <div class="pull-right">
            <span>Made by <a href="https://haroen.me">Haroen</a> for Odisee | </span>
            <span>🚀 Euro Space Center | </span>
            <span><a href="/Help">📑 API</a> | </span>
            <span><a href="https://github.com/Haroenv/mvc-euro-space-center"><span class="emoji">⚙</span> code</a> | </span>
            <span><a href="http://spacefun.umutsaglam.ikdoeict.net">🛰 Space Fun</a> | </span>
            <span><a href="http://marspark.eliasmeire.ikdoeict.net/">🌌 Mars Park</a></span>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>