EuroSpaceCenter/Controllers/AdminController.cs
using EuroSpaceCenter.Models;
using EuroSpaceCenter.util;
using System;
using System.Web.Mvc;

namespace EuroSpaceCenter.Controllers {
    [CustomAuthorize(Roles = "admin")]
    public class AdminController : Controller {
        // GET: Admin
        public ViewResult Index() {
            ViewBag.Restaurants = item.Get("restaurants");
            ViewBag.Attractions = item.Get("attractions");
            ViewBag.Shows = item.Get("shows");
            return View();
        }

        // GET: Admin/Create
        public ViewResult Create(string cat) {
            ViewBag.category = cat;
            return View();
        }

        // POST: Admin/create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(item i) {
            if (TryValidateModel(i)) {
                try {
                    item.Create(i);
                    switch (Request["category"]) {
                        case "restaurant":
                            var r = new restaurant() {
                                items_id = i.id,
                                payment_type = Request["payment_type"]
                            };
                            if (TryValidateModel(r)) {
                                restaurant.Create(r);

                            } else {
                                Flash.Set(TempData, "oops, wrong extras! 😬");
                                return View(i);
                            }
                            break;
                        case "show":
                            var s = new show() {
                                items_id = i.id,
                                datetime = DateTime.Parse(Request["datetime"])
                            };
                            if (TryValidateModel(s)) {
                                show.Create(s);
                            } else {
                                Flash.Set(TempData, "oops, wrong extras! 😬");
                                return View(i);
                            }
                            break;
                        case "attraction":
                            var a = new attraction() {
                                items_id = i.id,
                                max_height = int.Parse(Request["max_height"]),
                                min_height = int.Parse(Request["min_height"])
                            };
                            if (TryValidateModel(a)) {
                                attraction.Create(a);
                            } else {
                                Flash.Set(TempData, "oops, wrong extras! 😬");
                                return View(i);
                            }
                            break;
                        default:
                            break;
                    }
                } catch {
                    Flash.Set(TempData, "something went wrong! 😬");
                    return View(i);
                }
                Flash.Set(TempData, "Created 🍻");
                return RedirectToAction("Index", "Detail", i.id);
            }
            Flash.Set(TempData, "oops! 😬");
            return View(i);
        }

        public ActionResult Ratings() {
            return View(rating.GetAll());
        }

        public RedirectToRouteResult DeleteRating(int id) {
            rating.Delete(id);
            Flash.Set(TempData, "That's gone! 💨");
            return RedirectToAction("Ratings");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public RedirectResult Show(int? id, show i) {
            try {
                i.items_id = (int)id;
                show.Update(i);
                Flash.Set(TempData, "Yep! Updated");
            } catch (Exception e) {
                Flash.Set(TempData, "Ay caramba, I made a mistake 😦" + e);
            }
            return Redirect("/Detail/?id=" + item.Get((int)id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public RedirectResult Attraction(int? id, attraction i) {
            try {
                i.items_id = (int)id;
                attraction.Update(i);
                Flash.Set(TempData, "Boom! Updated");
            } catch (Exception) {
                Flash.Set(TempData, "Something went wrong 😦");
            }
            return Redirect("/Detail/?id=" + item.Get((int)id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public RedirectResult Restaurant(int? id, restaurant i) {
            try {
                i.items_id = (int)id;
                restaurant.Update(i);
                Flash.Set(TempData, "Bam! Updated");
            } catch (Exception) {
                Flash.Set(TempData, "Sorry 😦");
            }
            return Redirect("/Detail/?id=" + item.Get((int)id));
        }

        public RedirectResult Delete(int id) {
            item.Delete(id);
            Flash.Set(TempData, "That's gone! 💨");
            return Redirect("/Search");
        }

        public PartialViewResult Extra(string category) {
            ViewBag.category = category;
            return PartialView();
        }
    }
}

EuroSpaceCenter/Controllers/DetailController.cs
using EuroSpaceCenter.Models;
using EuroSpaceCenter.util;
using System;
using System.Linq;
using System.Web.Mvc;

namespace EuroSpaceCenter.Controllers {
    public class DetailController : Controller {
        // GET: Detail?id={id}
        public ActionResult Index(int? id) {
            if (id == null) {
                return Redirect("/Search");
            }
            item i = item.Get((int)id);
            if (i == null) {
                return Redirect("/Search");
            }

            ViewBag.Ratings = i.ratings.ToList();
            ViewBag.Score = i.ratings.Any() ? i.ratings.Average(r => r.rating1) : double.NaN;
            ViewBag.Rating = new rating();
            ViewBag.ID = id;

            if (i.attraction != null) {
                ViewBag.Properties = i.attraction.GetType().GetProperties().Where(itm => itm.Name != "item" && itm.Name != "items_id");
                ViewBag.PropModel = i.attraction;
            } else if (i.show != null) {
                ViewBag.Properties = i.show.GetType().GetProperties().Where(itm => itm.Name != "item" && itm.Name != "items_id");
                ViewBag.PropModel = i.show;
            } else if (i.restaurant != null) {
                ViewBag.Properties = i.restaurant.GetType().GetProperties().Where(itm => itm.Name != "item" && itm.Name != "items_id");
                ViewBag.PropModel = i.restaurant;
            }
            if (User.Identity.IsAuthenticated) {
                ViewBag.Parkplans = parkplan.GetAll(user.Get(User.Identity.Name).id).Where(uhp => uhp.accepted).Select(uhp => uhp.parkplan);
            }
            return View(i);
        }

        // POST Detail/Rate/
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Rate(rating r) {
            try {
                if (ModelState.IsValid) {
                    r.users_id = user.Get(User.Identity.Name).id;
                    r.datetime = DateTime.Now;
                    rating.Rate(r);
                    Flash.Set(TempData, "Rated! 🍾");
                    return Redirect("/Detail?id=" + r.items_id);
                }
                item i = item.Get(r.items_id);
                ViewBag.Ratings = rating.Get(r.items_id);
                ViewBag.id = r.items_id;
                ViewBag.Rating = r;
                Flash.Set(TempData, "You forgot to fill in something 😧");
                return View("Index", i);
            } catch {
                Flash.Set(TempData, "Something went wrong 😕");
                return Redirect("/Detail?id=" + r.items_id);
            }
        }

        [CustomAuthorize(Roles = "admin")]
        public ActionResult Edit(int? id) {
            if (id == null) {
                Flash.Set(TempData, "You didn't supply an id 🆔");
                return Redirect("/Search");
            }
            item i = item.Get((int)id);
            if (i == null) {
                Flash.Set(TempData, "This item doesn't exist 😞");
                return Redirect("/Search");
            }
            return View(i);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        [CustomAuthorize(Roles = "admin")]
        public ActionResult Edit(item i) {
            if (TryValidateModel(i)) {
                item result = item.Update(i);
                Flash.Set(TempData, "Updated 🍻");
                return RedirectToAction("Index", "Detail", i.id);
            }
            Flash.Set(TempData, "oops! 😬");
            return View(i);
        }
    }
}

EuroSpaceCenter/Controllers/PlanController.cs
using EuroSpaceCenter.Models;
using EuroSpaceCenter.util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace EuroSpaceCenter.Controllers {
    [Authorize]
    public class PlanController : Controller {

        public ActionResult Index() {
            List<users_has_parkplan> all = parkplan.GetAll(user.Get(User.Identity.Name).id);
            var accepted = all.Where(uhp => uhp.accepted).Select(uhp => uhp.parkplan);
            ViewBag.UnAccepted = all.Where(uhp => !uhp.accepted).Select(uhp => uhp.parkplan);
            return View(accepted);
        }

        // plans are public on purpose
        public ActionResult Detail(int id) {
            var plan = parkplan.Get(parkplan_id: id);
            ViewBag.Items = item.GetAll();
            ViewBag.PlanItems = plan.parkplans_has_items.ToList();
            ViewBag.Users = plan.users_has_parkplans.Select(t => t.user);
            return View(plan);
        }

        public HttpStatusCodeResult Set(int id) {
            if (parkplan.HasUser(user_id: user.Get(User.Identity.Name).id, parkplan_id: id)) {
                Session.Add("plan", new { id = id });
                return new HttpStatusCodeResult(200);
            } else {
                return new HttpStatusCodeResult(403);
            }
        }

        public ActionResult Create() {
            return View();
        }

        [HttpPost]
        public HttpStatusCodeResult Delete(int id) {
            try {
                if (parkplan.HasUser(user_id: user.Get(User.Identity.Name).id, parkplan_id: id)) {
                    parkplan.Delete(id);
                    return new HttpStatusCodeResult(204);
                } else {
                    return new HttpStatusCodeResult(403);
                }
            } catch (Exception) {
                return new HttpStatusCodeResult(500);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(parkplan plan) {
            if (TryValidateModel(plan)) {
                var p = plan.Create(user.Get(User.Identity.Name).id);
                return RedirectToAction("Detail", new { id = p.id });
            }
            return View(plan);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Invite(int id, string email) {
            // parkplan needs to be yours
            if (parkplan.HasUser(parkplan_id: id, user_id: user.Get(User.Identity.Name).id)) {
               try {
                    var u = user.Get(email);
                    // does invitee exist?
                    if (u == null) {
                        Email.Send(email, null, $"Your friend just signed you up for ESC, but you didn't have an account yet. You can Register at this link", "Log In", "http://eurospacecenter.haroenviaene.ikdoeict.be/Register/Index?plan=" + id, "Invited");
                        Flash.Set(TempData, "This user didn't have an account yet, they are invited now!");
                        return RedirectToAction("Detail", new { id = id });
                    } else {
                        parkplan.Invite(users_id: u.id, parkplan_id: id);
                        Flash.Set(TempData, "Invited");
                        return RedirectToAction("Detail", new { id = id });
                    }
                } catch (Exception e) {
                    Flash.Set(TempData, "That didn't work 😲");
                    return RedirectToAction("Detail", new { id = id });
                }
            }
            Flash.Set(TempData, "That's not your plan 💁");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Add(int id, int item_id) {
            try {
                if (parkplan.HasUser(parkplan_id: id, user_id: user.Get(User.Identity.Name).id)) {
                    int has_id = parkplan.AddItem(id, item_id);
                    return Json(new { id = has_id });
                }
                return new HttpStatusCodeResult(403);
            } catch {
                return new HttpStatusCodeResult(500);
            }
        }

        [HttpPost]
        public HttpStatusCodeResult Remove(int id, int plan_has_item) {
            if (parkplan.HasUser(parkplan_id: id, user_id: user.Get(User.Identity.Name).id)) {
                parkplan.RemoveItem(plan_has_item);
                return new HttpStatusCodeResult(204);
            }
            return new HttpStatusCodeResult(403);
        }

        [HttpPost]
        public HttpStatusCodeResult Accept(int id) {
            if (parkplan.HasUser(parkplan_id: id, user_id: user.Get(User.Identity.Name).id)) {
                parkplan.Accept(user.Get(User.Identity.Name).id, id);
                return new HttpStatusCodeResult(200);
            }
            return new HttpStatusCodeResult(403);
        }

        [HttpPost]
        public HttpStatusCodeResult Reject(int id) {
            if (parkplan.HasUser(parkplan_id: id, user_id: user.Get(User.Identity.Name).id)) {
                parkplan.Reject(user.Get(User.Identity.Name).id, id);
                return new HttpStatusCodeResult(204);
            }
            return new HttpStatusCodeResult(403);
        }
    }
}

EuroSpaceCenter/Views/Detail/Edit.cshtml
@model EuroSpaceCenter.Models.item

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container container--small">

    <h2>Create a new <span id="type">item</span></h2>

    @using (Html.BeginForm("Edit", "Detail", FormMethod.Post, new { @id = "mainform" })) {
        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(i => i.title)
            @Html.EditorFor(i => i.title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(i => i.title, null, new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(i => i.description)
            @Html.TextAreaFor(i => i.description, new { @class = "form-control" })
            @Html.ValidationMessageFor(i => i.description, null, new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(i => i.image)
            @Html.EditorFor(i => i.image, new { htmlAttributes = new { @class = "form-control", inputmode = "url", placeholder = "url to the image of this item", oninput = "preview.src = this.value" } })
            @Html.ValidationMessageFor(i => i.image, null, new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <label for="preview">preview</label>
            <img class="img-responsive" id="preview" />
        </div>
        <div class="form-group">
            @Html.LabelFor(i => i.alt)
            @Html.EditorFor(i => i.alt, new { htmlAttributes = new { @class = "form-control", placeholder = "description of the image for non-sighted users" } })
            @Html.ValidationMessageFor(i => i.alt, null, new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.Button("edit 📝", new { @class = "btn btn-primary" })
        </div>
    }


    @using (Html.BeginForm("Update", "Admin", FormMethod.Post, new { id = "extraform" })) {
        @Html.AntiForgeryToken()
        <h3>Add extra info</h3>
        <div class="form-group">
            <label for="category">category</label>
            <select id="category" name="category" class="form-control">
                <option value="null">-- pick a category --</option>
                <option value="attraction">Attraction</option>
                <option value="show">Show</option>
                <option value="restaurant">Restaurant</option>
            </select>
        </div>
        <fieldset disabled id="extra" class="form-group"></fieldset>
        <div class="form-group">
            @Html.Button("add ✔️", new { @class = "btn btn-primary" })
        </div>
    }
</div>

@section scripts {
    <script>
        function loadExtra(category) {
            $('#extraform').attr('action', '/Admin/' + category + '?id=@Model.id');
            $("#extra").load(
                "@Url.Action("Extra","Admin")",
                { 'category': category },
                function (response, status, xhr) {
                    if (status == "error") {
                        alert("An error occurred while loading the results.");
                    } else {
                        $('#extra').removeAttr('disabled');
                    }
                });
        }

        $(document).ready(function () {
            $("#category").on("input", function (e) {
                loadExtra(e.target.value);
            });
            if ("@ViewBag.category".length > 0) {
                loadExtra("@ViewBag.category");
                $("#category").val("@ViewBag.category");
            }
        });
    </script>
}

EuroSpaceCenter/Views/Detail/Index.cshtml
@using EuroSpaceCenter.Models
@model item

@{
    ViewBag.Title = Model.title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>
    @Model.title
    @if (ViewBag.PropModel != null) {
        <span class="label label-info">@ViewBag.PropModel.GetType().Name</span>
    }
    @if (ViewBag.Score != double.NaN) {
        <span data-rating="@Math.Ceiling(ViewBag.Score)">@Math.Ceiling(ViewBag.Score) / 5</span>
    }
    @if (User.IsInRole("admin")) {
        @Html.ActionLink("Edit", "Edit", new { id = @Model.id }, new { @class = "btn btn-success" })
    }
</h2>

<div class="row">
    <div class="col-md-5">
        <img src="@Model.image" alt="@Model.alt" class="img-responsive img-rounded" />
    </div>
    <div class="col-md-7">
        <section class="panel panel-default" id="description">
            <div class="panel-heading">
                <h4>Description</h4>
            </div>
            <p class="panel-body">@Model.description</p>
        </section>
        @if (ViewBag.Properties != null) {
            <section class="panel panel-default" id="details">
                <div class="panel-heading">
                    <h4>Details</h4>
                </div>
                <div class="panel-body">
                    <dl class="dl-horizontal">
                        @foreach (var property in ViewBag.Properties) {
                            <dt>@property.Name</dt>
                            //doesn't work because the type isn't sure on beforehand 😞
                            @*<dt>@property.GetCustomAttribute<DisplayAttribute>().GetName()</dt>*@
                            <dd>@property.GetValue(ViewBag.PropModel, null)</dd>
                        }
                    </dl>
                </div>
            </section>
        }
        @if (User.Identity.IsAuthenticated) {
            using (Html.BeginForm("Add", "Plan", FormMethod.Post, new { id = "addToPlan" })) {
                @Html.AntiForgeryToken()
                <input type="hidden" name="items_id" value="@ViewBag.ID" />
                <label for="id">Add this item to your <a href="/Plan">park plan <span class="emoji">🗺</span></a></label>
                <div class="input-group">
                    <select name="id" id="id" class="form-control">
                        @foreach (parkplan plan in ViewBag.Parkplans) {
                            <option value="@plan.id">@plan.name</option>
                        }
                    </select>
                    <div class="input-group-btn">
                        @Html.Button("Add", new { @class = "btn btn-success", id = "add", title = "yay 🎉" })
                    </div>
                </div>
            }
        }
    </div>
</div>

@if (User.Identity.IsAuthenticated) {

    @Html.Partial("Review", (rating)ViewBag.Rating)
}


<section id="ratings">
    <h3>Reviews</h3>
    <div class="row">
        @foreach (rating r in ViewBag.Ratings) {
            <div class="col-sm-1">
                <div class="thumbnail">
                    @Html.GravatarImage(r.user.email)
                </div>
            </div>
            <div class="col-sm-5">
                <div class="panel panel-default">
                    <div class="panel-heading clearfix">
                        <div class="pull-left">
                            <strong>@r.user.name</strong>
                            @Html.Time(r.datetime, "{0:d}", new { @class = "text-muted" })
                        </div>
                        <strong class="pull-right" data-rating="@r.rating1">@r.rating1 / 5</strong>
                    </div>
                    <div class="panel-body">
                        @r.message
                    </div>
                </div>
            </div>
        }
    </div>
</section>

@section scripts {
    <script>
        NodeList.prototype.forEach = Array.prototype.forEach; // polyfill
        var ratings = document.querySelectorAll('[data-rating]');
        ratings.forEach(function (r) {
            r.innerText = '☄'.repeat(r.dataset.rating) + '⚪'.repeat(5 - r.dataset.rating);
            r.classList.add('emoji');
        });

        $('#addToPlan').on('submit', function (e) {
            e.preventDefault();
            $(this).find('[name="id"]').val();
            $.ajax({
                method: 'POST',
                url: '/Plan/Add/' + $(this).find('[name="id"]').val() + '?item_id=@Model.id',
                success: function () {
                    $(e.target).find('button').tooltip({ placement: 'bottom', trigger: 'manual' }).tooltip('show');
                }
            })
        });
    </script>
}

EuroSpaceCenter/Views/Detail/Review.cshtml
@model EuroSpaceCenter.Models.rating

@using (Html.BeginForm("Rate", "Detail", FormMethod.Post)) {
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="message">Message</label>
        @Html.TextArea("message", new { @class = "form-control", required = "required" })
        @Html.ValidationMessageFor(model => model.message, "", new { @class = "text-danger" })
    </div>
        <div class="form-group">
            <label for="rating1">Rating</label>
            <input type="range" min="1" max="5" step="1" name="rating1" id="rating1" class="form-control" oninput="this.dataset.value = this.value" required />
            @Html.ValidationMessageFor(model => model.rating1, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.Button("review", new { @class = "btn btn-success" })
        </div>
        <input type="hidden" name="items_id" value="@ViewBag.id" id="items_id" />
}